# this is workflow name
name: Hello Vikas

on:
  push:
    branches: [main]
    
#these are jobs inside the workflow
jobs:

  # this is the name of job
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to dosto
        run: echo "hello dosto"

      - name: say hello to Vikas
        run: echo "hello $USER"
      
